# -*- coding: utf-8 -*-
"""Aula3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vqcay0pesoyZwhZnVweunK0iIuIjej3m
"""

import pandas as pd

"""# Importar dataset (código copiado do site kaggle)"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("dhanushnarayananr/credit-card-fraud")

print("Path to dataset files:", path)

"""# Criar dataframe com o Pandas"""

import os

path_csv = os.path.join(path, 'card_transdata.csv')


df = pd.read_csv(path_csv)

"""# Visualizar as primeiras 5 linhas"""

display(df.head())

"""# Obter um resumo das informações"""

display(df.info())

"""# Obter estatisticas descritivas para colunas numericas"""

display(df.describe())

"""# Contagem de valores ausentes"""

print(df.isnull().sum())

"""# Resultado da analise de valores ausentes:
Nao encontramos nenhum dado ausente para ser tratato.

# Contagem de valores duplicados
"""

print(df.duplicated().sum())

"""# Resultado da analise de valores duplicados:
Nao encontramos nenhum valor duplicado para ser tratato.

# Importar bibliotecas de visualizacao
"""

import matplotlib.pyplot as plt
import seaborn as sns

"""# Escolher uma coluna numerica para visualizar"""

coluna_analise = 'distance_from_home'

if coluna_analise in df.columns and pd.api.types.is_numeric_dtype(df[coluna_analise]):
    print(f"-- ANALISANDO OUTLIERS NA COLUNA: '{coluna_analise}'")

    plt.figure(figsize=(10, 6))
    sns.boxplot(x=df[coluna_analise])
    plt.title(f"Boxplot da coluna '{coluna_analise}'")
    plt.show()

"""# Resultado da analise de outliers:
Encontramos alguns outliers, mas não vamos remover eles pois acreditamos que os dados estao corretos.
"""